spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3305/mldn8001
    username: root
    password:
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
  application:
    name: microcloud-provider-dept
server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
    instance-id: deptdev-8001.com
  client:
    service-url:
      defaultZone: http://hang:hang@eureka-7001.com:7001/eureka
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.baskman.vo

---
spring:
  profiles: beta
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3305/mldn8001
    username: root
    password:
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
  application:
    name: microcloud-provider-dept
server:
  port: 8001
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://hang:hang@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: deptbeta-8001.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.baskman.vo